import {ColumnFilter} from "../ColumnFilter";



export const screen1Column=[
  { Header: "ID", accessor: "id",Filter:ColumnFilter },              
  { Header: "First Name", accessor: "first_name",Filter:ColumnFilter  },
  { Header: "Last Name", accessor: "last_name",Filter:ColumnFilter  },
  { Header: "Email", accessor: "email",Filter:ColumnFilter  },
  { Header: "Gender", accessor: "gender",Filter:ColumnFilter  },
  { Header: "Age", accessor: "age",Filter:ColumnFilter  },
 ];

 export const screen1Data= [
  {"id":1,"first_name":"Michael","last_name":"Follen","email":"mfollen0@studiopress.com","gender":"Male","age":664},
{"id":2,"first_name":"Suzy","last_name":"Stedman","email":"sstedman1@whitehouse.gov","gender":"Female","age":523},
{"id":3,"first_name":"Derry","last_name":"Shelper","email":"dshelper2@princeton.edu","gender":"Male","age":40},
{"id":4,"first_name":"Birk","last_name":"Pauletto","email":"bpauletto3@netlog.com","gender":"Male","age":333},
{"id":5,"first_name":"Alaric","last_name":"Golsworthy","email":"agolsworthy4@php.net","gender":"Male","age":553},
{"id":6,"first_name":"Winnie","last_name":"Ansett","email":"wansett5@sfgate.com","gender":"Male","age":68},
{"id":7,"first_name":"Cointon","last_name":"Larmouth","email":"clarmouth6@dedecms.com","gender":"Male","age":636},
{"id":8,"first_name":"Grace","last_name":"Barock","email":"gbarock7@mozilla.com","gender":"Male","age":474},
{"id":9,"first_name":"Alexine","last_name":"Daville","email":"adaville8@ucoz.ru","gender":"Female","age":253},
{"id":10,"first_name":"Tobin","last_name":"Lassells","email":"tlassells9@msu.edu","gender":"Male","age":95},
{"id":11,"first_name":"Marion","last_name":"Mawne","email":"mmawnea@columbia.edu","gender":"Female","age":677},
{"id":12,"first_name":"Bryn","last_name":"O' Culligan","email":"boculliganb@alibaba.com","gender":"Male","age":359},
{"id":13,"first_name":"Virgie","last_name":"Medway","email":"vmedwayc@ibm.com","gender":"Female","age":576},
{"id":14,"first_name":"Ambrosius","last_name":"Attridge","email":"aattridged@dailymotion.com","gender":"Male","age":388},
{"id":15,"first_name":"Julee","last_name":"Antonellini","email":"jantonellinie@nhs.uk","gender":"Female","age":638},
{"id":16,"first_name":"Ros","last_name":"Delea","email":"rdeleaf@exblog.jp","gender":"Female","age":627},
{"id":17,"first_name":"Dara","last_name":"Harner","email":"dharnerg@europa.eu","gender":"Female","age":415},
{"id":18,"first_name":"Jasen","last_name":"Capnerhurst","email":"jcapnerhursth@state.tx.us","gender":"Male","age":271},
{"id":19,"first_name":"Prudence","last_name":"Mattiassi","email":"pmattiassii@quantcast.com","gender":"Bigender","age":515},
{"id":20,"first_name":"Bethena","last_name":"Pelling","email":"bpellingj@squidoo.com","gender":"Female","age":718},
{"id":21,"first_name":"Alistair","last_name":"Buckley","email":"abuckleyk@taobao.com","gender":"Male","age":143},
{"id":22,"first_name":"Radcliffe","last_name":"Skryne","email":"rskrynel@fda.gov","gender":"Male","age":324},
{"id":23,"first_name":"Amii","last_name":"Nutten","email":"anuttenm@yahoo.com","gender":"Female","age":576},
{"id":24,"first_name":"Ermin","last_name":"Threadkell","email":"ethreadkelln@technorati.com","gender":"Male","age":515},
{"id":25,"first_name":"Kara-lynn","last_name":"Dagnall","email":"kdagnallo@sfgate.com","gender":"Female","age":418},
{"id":26,"first_name":"Cherice","last_name":"Beine","email":"cbeinep@domainmarket.com","gender":"Female","age":37},
{"id":27,"first_name":"Darda","last_name":"Kopman","email":"dkopmanq@blog.com","gender":"Polygender","age":113},
{"id":28,"first_name":"Catlee","last_name":"Berardt","email":"cberardtr@wikipedia.org","gender":"Female","age":605},
{"id":29,"first_name":"Morlee","last_name":"Skillington","email":"mskillingtons@barnesandnoble.com","gender":"Male","age":239},
{"id":30,"first_name":"Christa","last_name":"Frake","email":"cfraket@de.vu","gender":"Female","age":694},
{"id":31,"first_name":"Bernice","last_name":"De Luna","email":"bdelunau@samsung.com","gender":"Female","age":514},
{"id":32,"first_name":"Cosme","last_name":"Hensmans","email":"chensmansv@ihg.com","gender":"Male","age":390},
{"id":33,"first_name":"Dorita","last_name":"Goldsbrough","email":"dgoldsbroughw@list-manage.com","gender":"Female","age":593},
{"id":34,"first_name":"Dennet","last_name":"Delbergue","email":"ddelberguex@mapquest.com","gender":"Male","age":657},
{"id":35,"first_name":"Leese","last_name":"Drains","email":"ldrainsy@sphinn.com","gender":"Female","age":517},
{"id":36,"first_name":"Dania","last_name":"Kiltie","email":"dkiltiez@mit.edu","gender":"Female","age":424},
{"id":37,"first_name":"Ardith","last_name":"Yerill","email":"ayerill10@craigslist.org","gender":"Female","age":659},
{"id":38,"first_name":"Iolanthe","last_name":"Verne","email":"iverne11@chronoengine.com","gender":"Female","age":318},
{"id":39,"first_name":"Stanislas","last_name":"Scamaden","email":"sscamaden12@infoseek.co.jp","gender":"Male","age":181},
{"id":40,"first_name":"Arv","last_name":"Labbey","email":"alabbey13@amazonaws.com","gender":"Male","age":161},
{"id":41,"first_name":"Charmane","last_name":"Vanyatin","email":"cvanyatin14@epa.gov","gender":"Female","age":443},
{"id":42,"first_name":"Stanleigh","last_name":"Harback","email":"sharback15@360.cn","gender":"Male","age":555},
{"id":43,"first_name":"Marianna","last_name":"Manuaud","email":"mmanuaud16@bloglovin.com","gender":"Female","age":658},
{"id":44,"first_name":"Lucian","last_name":"Douglass","email":"ldouglass17@purevolume.com","gender":"Male","age":146},
{"id":45,"first_name":"Antony","last_name":"Goundsy","email":"agoundsy18@w3.org","gender":"Male","age":612},
{"id":46,"first_name":"Bernice","last_name":"Patis","email":"bpatis19@vk.com","gender":"Female","age":114},
{"id":47,"first_name":"Claus","last_name":"Manilow","email":"cmanilow1a@bing.com","gender":"Male","age":608},
{"id":48,"first_name":"Darla","last_name":"Mattioni","email":"dmattioni1b@vimeo.com","gender":"Female","age":266},
{"id":49,"first_name":"Merry","last_name":"Ayrs","email":"mayrs1c@cargocollective.com","gender":"Female","age":578},
{"id":50,"first_name":"Blanch","last_name":"Reed","email":"breed1d@apache.org","gender":"Female","age":661},
]
 



 export const screen2Column=[
   { Header: "ID", accessor: "id" },              
   { Header: "Car Model", accessor: "car_model" },
   { Header: "Car Make", accessor: "car_make" },
   { Header: "Model Year", accessor: "car_model_year" },
 ]


 export const screen2Data=[{"id":1,"car_model":"Sable","car_make":"Mercury","car_model_year":1996},
 {"id":2,"car_model":"Jetta","car_make":"Volkswagen","car_model_year":2001},
 {"id":3,"car_model":"Montero","car_make":"Mitsubishi","car_model_year":1997},
 {"id":4,"car_model":"E-Class","car_make":"Mercedes-Benz","car_model_year":2009},
 {"id":5,"car_model":"B-Series","car_make":"Mazda","car_model_year":1998},
 {"id":6,"car_model":"Skylark","car_make":"Buick","car_model_year":1993},
 {"id":7,"car_model":"Astro","car_make":"Chevrolet","car_model_year":2005},
 {"id":8,"car_model":"HS","car_make":"Lexus","car_model_year":2012},
 {"id":9,"car_model":"Rapide","car_make":"Aston Martin","car_model_year":2010},
 {"id":10,"car_model":"Allroad","car_make":"Audi","car_model_year":2004},
 {"id":11,"car_model":"Camry","car_make":"Toyota","car_model_year":2008},
 {"id":12,"car_model":"Tracker","car_make":"Geo","car_model_year":1993},
 {"id":13,"car_model":"Century","car_make":"Buick","car_model_year":1986},
 {"id":14,"car_model":"Ram Wagon B250","car_make":"Dodge","car_model_year":1993},
 {"id":15,"car_model":"Trans Sport","car_make":"Pontiac","car_model_year":1994},
 {"id":16,"car_model":"Rio","car_make":"Kia","car_model_year":2010},
 {"id":17,"car_model":"E-Class","car_make":"Mercedes-Benz","car_model_year":1984},
 {"id":18,"car_model":"Avalon","car_make":"Toyota","car_model_year":2012},
 {"id":19,"car_model":"Cabriolet","car_make":"Volkswagen","car_model_year":1992},
 {"id":20,"car_model":"Sierra 2500","car_make":"GMC","car_model_year":1999},
 {"id":21,"car_model":"Galant","car_make":"Mitsubishi","car_model_year":2012},
 {"id":22,"car_model":"Viper RT/10","car_make":"Dodge","car_model_year":1994},
 {"id":23,"car_model":"SL-Class","car_make":"Mercedes-Benz","car_model_year":2002},
 {"id":24,"car_model":"Tacoma","car_make":"Toyota","car_model_year":1998},
 {"id":25,"car_model":"Mark VIII","car_make":"Lincoln","car_model_year":1994},
 {"id":26,"car_model":"Pajero","car_make":"Mitsubishi","car_model_year":1984},
 {"id":27,"car_model":"Grand Cherokee","car_make":"Jeep","car_model_year":2003},
 {"id":28,"car_model":"Diamante","car_make":"Mitsubishi","car_model_year":1995},
 {"id":29,"car_model":"Wrangler","car_make":"Jeep","car_model_year":1994},
 {"id":30,"car_model":"S2000","car_make":"Honda","car_model_year":2004},
 {"id":31,"car_model":"Metro","car_make":"Chevrolet","car_model_year":1999},
 {"id":32,"car_model":"Legacy","car_make":"Subaru","car_model_year":1995},
 {"id":33,"car_model":"tC","car_make":"Scion","car_model_year":2011},
 {"id":34,"car_model":"Stratus","car_make":"Dodge","car_model_year":1996},
 {"id":35,"car_model":"ES","car_make":"Lexus","car_model_year":1998},
 {"id":36,"car_model":"S10","car_make":"Chevrolet","car_model_year":2004},
 {"id":37,"car_model":"TT","car_make":"Audi","car_model_year":2012},
 {"id":38,"car_model":"Protege","car_make":"Mazda","car_model_year":1999},
 {"id":39,"car_model":"Fit","car_make":"Honda","car_model_year":2010},
 {"id":40,"car_model":"F250","car_make":"Ford","car_model_year":2002},
 {"id":41,"car_model":"Sierra 3500","car_make":"GMC","car_model_year":2000},
 {"id":42,"car_model":"Bravada","car_make":"Oldsmobile","car_model_year":2004},
 {"id":43,"car_model":"Range Rover Sport","car_make":"Land Rover","car_model_year":2012},
 {"id":44,"car_model":"SRX","car_make":"Cadillac","car_model_year":2005},
 {"id":45,"car_model":"S80","car_make":"Volvo","car_model_year":1999},
 {"id":46,"car_model":"MPV","car_make":"Mazda","car_model_year":2003},
 {"id":47,"car_model":"Camry","car_make":"Toyota","car_model_year":2005},
 {"id":48,"car_model":"Yukon XL 1500","car_make":"GMC","car_model_year":2000},
 {"id":49,"car_model":"Sable","car_make":"Mercury","car_model_year":2003},
 {"id":50,"car_model":"330","car_make":"BMW","car_model_year":2005}]

